### ISSUE TITLE
Different behavior when searching for number ranges

### ISSUE THREAD

**Issue by SimonThunborg** [Neovici/cosmoz-omnitable#66] opened 2017-10-19 09:45 UTC
If the user search for e.g amounts from 0 to 0 the search/filter automatically changes to 0 to 0.03. 
![omnitable - number range](https://user-images.githubusercontent.com/32709706/31764872-c583cdc4-b4c2-11e7-85a7-b7b7e344bd2d.png)

**Comment by nomego** [comment] 2018-06-18 10:18
We need a way to reproduce this @SimonThunborg

**Comment by JockeCK** [comment] 2018-10-29 14:05
Closing this after discussion with Simon. We could not reproduce it.

**Closed by JockeCK** 2018-10-29 14:05 UTC
Labels: help wanted
